#!/bin/bash

printf "\n\n........................................\n"
printf '\e[1;34m%-6s\e[m' "Compiling vcALE initial conditions"
printf "\n........................................\n\n"

wclean && wmake -update -j
